controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# << Post Routes >>

getPostList:
    path: /
    controller: App\Controller\PostController::getList
    methods: [ GET ]

getPostForm:
    path: /post/new
    controller: App\Controller\PostController::getForm
    methods: [ GET ]

postPost:
    path: /post/new
    controller: App\Controller\PostController::post
    methods: [ POST ]

getPost:
    path: /post/{post_id}
    controller: App\Controller\PostController::get
    methods: [ GET ]

postPostLike:
    path: /post/{post_id}/like
    controller: App\Controller\PostController::postLike
    methods: [ POST ]

# << Comment Routes >>

postPostComment:
    path: /post/{post_id}
    controller: App\Controller\CommentController::postPost
    methods: [ POST ]

postCommentComment:
    path: /post/{post_id}/{comment_id}
    controller: App\Controller\CommentController::postComment
    methods: [ POST ]

postLikeComment:
    path: /post/{post_id}/{comment_id}/like
    controller: App\Controller\CommentController::postLike
    methods: [ POST ]

postDeleteComment:
    path: /admin/comment/{comment_id}/delete
    controller: App\Controller\CommentController::postDelete
    methods: [ POST ]

# << User Routes >>

getUserRegister:
    path: /user/register
    controller: App\Controller\UserController::register
    methods: [ GET, POST ]

getUserLogin:
    path: /user/login
    controller: App\Controller\UserController::login
    methods: [ GET, POST ]

getUserLogout:
    path: /user/logout
    controller: App\Controller\UserController::logout
    methods: [ GET ]

postBlockUser:
    path: /admin/user/{user_id}/block
    controller: App\Controller\UserController::block
